apiVersion: v1
kind: Pod
metadata:
  name: grace
spec:
  containers:
    - name: grace
      image: optihack/httpserver:v1.0
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
      lifecycle:
        preStop:
          exec:
            command: ["echo","grace stop..."]
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests:
          memory: "200Mi"
          cpu: "200m"
